### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by erkan377** [Ziome3eg/G25_Pedals_and_Shifter#1]
![image](https://user-images.githubusercontent.com/85454251/230593419-fba9675a-c915-41d3-a582-7d05a4005288.png)
le câblage et t'il correcte ?

**Comment by erkan377** [comment]
quand je branche ma boite de vitesse l'aduino s'éteins

**Comment by erkan377** [comment]
j'ai trouvé je m'etait trompé dans les connecteur je l'ai ai inverser, quelle qu'un pourrais rajouter les boutons qui sont sur la boite de vitesse ? pour l'instant la boite ne fonctionne pas aussi je dois trouver pourquoi

**Comment by EngAAlex** [comment]
> j'ai trouvé je m'etait trompé dans les connecteur je l'ai ai inverser, quelle qu'un pourrais rajouter les boutons qui sont sur la boite de vitesse ? pour l'instant la boite ne fonctionne pas aussi je dois trouver pourquoi

I had the same issue and fixed the pinout in this [other repository](https://github.com/EngAAlex/G25_Pedals_and_Shifter). I also opened a pull request on this one to fix it. Let me know if this works.
